// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// The values are loaded from compile-time environment variables (see
/// `configs/*.json` which are consumed via `--dart-define-from-file`).
/// This keeps sensitive keys out of source control and avoids shipping the
/// now-invalid sample Firebase project that originally shipped with the repo.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _FirebaseOptionsFactory.web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _FirebaseOptionsFactory.android;
      case TargetPlatform.iOS:
        return _FirebaseOptionsFactory.ios;
      case TargetPlatform.macOS:
        return _FirebaseOptionsFactory.macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'add the necessary FIREBASE_WINDOWS_* defines or reconfigure using the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'add the necessary FIREBASE_LINUX_* defines or reconfigure using the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}

class _FirebaseOptionsFactory {
  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _require(
          _FirebaseEnv.webApiKey,
          'FIREBASE_WEB_API_KEY',
          'web',
        ),
        appId: _require(
          _FirebaseEnv.webAppId,
          'FIREBASE_WEB_APP_ID',
          'web',
        ),
        messagingSenderId: _require(
          _FirebaseEnv.webMessagingSenderId,
          'FIREBASE_WEB_MESSAGING_SENDER_ID',
          'web',
        ),
        projectId: _require(
          _FirebaseEnv.webProjectId,
          'FIREBASE_WEB_PROJECT_ID',
          'web',
        ),
        authDomain: _require(
          _FirebaseEnv.webAuthDomain,
          'FIREBASE_WEB_AUTH_DOMAIN',
          'web',
        ),
        storageBucket: _require(
          _FirebaseEnv.webStorageBucket,
          'FIREBASE_WEB_STORAGE_BUCKET',
          'web',
        ),
        measurementId: _optional(_FirebaseEnv.webMeasurementId),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _require(
          _FirebaseEnv.androidApiKey,
          'FIREBASE_ANDROID_API_KEY',
          'android',
        ),
        appId: _require(
          _FirebaseEnv.androidAppId,
          'FIREBASE_ANDROID_APP_ID',
          'android',
        ),
        messagingSenderId: _require(
          _FirebaseEnv.androidMessagingSenderId,
          'FIREBASE_ANDROID_MESSAGING_SENDER_ID',
          'android',
        ),
        projectId: _require(
          _FirebaseEnv.androidProjectId,
          'FIREBASE_ANDROID_PROJECT_ID',
          'android',
        ),
        storageBucket: _require(
          _FirebaseEnv.androidStorageBucket,
          'FIREBASE_ANDROID_STORAGE_BUCKET',
          'android',
        ),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _require(
          _FirebaseEnv.iosApiKey,
          'FIREBASE_IOS_API_KEY',
          'ios',
        ),
        appId: _require(
          _FirebaseEnv.iosAppId,
          'FIREBASE_IOS_APP_ID',
          'ios',
        ),
        messagingSenderId: _require(
          _FirebaseEnv.iosMessagingSenderId,
          'FIREBASE_IOS_MESSAGING_SENDER_ID',
          'ios',
        ),
        projectId: _require(
          _FirebaseEnv.iosProjectId,
          'FIREBASE_IOS_PROJECT_ID',
          'ios',
        ),
        storageBucket: _require(
          _FirebaseEnv.iosStorageBucket,
          'FIREBASE_IOS_STORAGE_BUCKET',
          'ios',
        ),
        iosBundleId: _require(
          _FirebaseEnv.iosBundleId,
          'FIREBASE_IOS_BUNDLE_ID',
          'ios',
        ),
      );

  static FirebaseOptions get macos {
    if (_FirebaseEnv.macosApiKey.isEmpty) {
      throw UnsupportedError(
        'Firebase options have not been configured for macOS. '
        'Provide FIREBASE_MACOS_* dart defines if you need macOS builds.',
      );
    }

    return FirebaseOptions(
      apiKey: _require(
        _FirebaseEnv.macosApiKey,
        'FIREBASE_MACOS_API_KEY',
        'macos',
      ),
      appId: _require(
        _FirebaseEnv.macosAppId,
        'FIREBASE_MACOS_APP_ID',
        'macos',
      ),
      messagingSenderId: _require(
        _FirebaseEnv.macosMessagingSenderId,
        'FIREBASE_MACOS_MESSAGING_SENDER_ID',
        'macos',
      ),
      projectId: _require(
        _FirebaseEnv.macosProjectId,
        'FIREBASE_MACOS_PROJECT_ID',
        'macos',
      ),
      storageBucket: _require(
        _FirebaseEnv.macosStorageBucket,
        'FIREBASE_MACOS_STORAGE_BUCKET',
        'macos',
      ),
      iosBundleId: _require(
        _FirebaseEnv.macosBundleId,
        'FIREBASE_MACOS_BUNDLE_ID',
        'macos',
      ),
    );
  }
}

class _FirebaseEnv {
  const _FirebaseEnv._();

  // Web
  static const webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
    defaultValue: '',
  );
  static const webAppId = String.fromEnvironment(
    'FIREBASE_WEB_APP_ID',
    defaultValue: '',
  );
  static const webMessagingSenderId = String.fromEnvironment(
    'FIREBASE_WEB_MESSAGING_SENDER_ID',
    defaultValue: '',
  );
  static const webProjectId = String.fromEnvironment(
    'FIREBASE_WEB_PROJECT_ID',
    defaultValue: '',
  );
  static const webAuthDomain = String.fromEnvironment(
    'FIREBASE_WEB_AUTH_DOMAIN',
    defaultValue: '',
  );
  static const webStorageBucket = String.fromEnvironment(
    'FIREBASE_WEB_STORAGE_BUCKET',
    defaultValue: '',
  );
  static const webMeasurementId = String.fromEnvironment(
    'FIREBASE_WEB_MEASUREMENT_ID',
    defaultValue: '',
  );

  // Android
  static const androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: '',
  );
  static const androidAppId = String.fromEnvironment(
    'FIREBASE_ANDROID_APP_ID',
    defaultValue: '',
  );
  static const androidMessagingSenderId = String.fromEnvironment(
    'FIREBASE_ANDROID_MESSAGING_SENDER_ID',
    defaultValue: '',
  );
  static const androidProjectId = String.fromEnvironment(
    'FIREBASE_ANDROID_PROJECT_ID',
    defaultValue: '',
  );
  static const androidStorageBucket = String.fromEnvironment(
    'FIREBASE_ANDROID_STORAGE_BUCKET',
    defaultValue: '',
  );

  // iOS
  static const iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
    defaultValue: '',
  );
  static const iosAppId = String.fromEnvironment(
    'FIREBASE_IOS_APP_ID',
    defaultValue: '',
  );
  static const iosMessagingSenderId = String.fromEnvironment(
    'FIREBASE_IOS_MESSAGING_SENDER_ID',
    defaultValue: '',
  );
  static const iosProjectId = String.fromEnvironment(
    'FIREBASE_IOS_PROJECT_ID',
    defaultValue: '',
  );
  static const iosStorageBucket = String.fromEnvironment(
    'FIREBASE_IOS_STORAGE_BUCKET',
    defaultValue: '',
  );
  static const iosBundleId = String.fromEnvironment(
    'FIREBASE_IOS_BUNDLE_ID',
    defaultValue: '',
  );

  // macOS (optional)
  static const macosApiKey = String.fromEnvironment(
    'FIREBASE_MACOS_API_KEY',
    defaultValue: '',
  );
  static const macosAppId = String.fromEnvironment(
    'FIREBASE_MACOS_APP_ID',
    defaultValue: '',
  );
  static const macosMessagingSenderId = String.fromEnvironment(
    'FIREBASE_MACOS_MESSAGING_SENDER_ID',
    defaultValue: '',
  );
  static const macosProjectId = String.fromEnvironment(
    'FIREBASE_MACOS_PROJECT_ID',
    defaultValue: '',
  );
  static const macosStorageBucket = String.fromEnvironment(
    'FIREBASE_MACOS_STORAGE_BUCKET',
    defaultValue: '',
  );
  static const macosBundleId = String.fromEnvironment(
    'FIREBASE_MACOS_BUNDLE_ID',
    defaultValue: '',
  );
}

String _require(String value, String key, String platform) {
  if (value.isEmpty) {
    throw StateError(
      'Missing Firebase configuration for "$key" ($platform). '
      'Add it to your configs/<flavor>.json and pass it via --dart-define-from-file.',
    );
  }
  return value;
}

String? _optional(String value) => value.isEmpty ? null : value;
